file_train1: ../../data/cikm_spanish_train_20180516.txt
file_train2: ../../data/cikm_english_train_20180516.txt
file_test: ../../data/cikm_test_a_20180516.txt
file_train: ../../data/v2.0/ft_train.txt
file_test: ../../data/v2.0/ft_test.txt
file_es_vec: ../../data/fast_text_vectors_wiki.es.vec/wiki.es.vec
file_model: ../../data/v2.0/ft_model.bin
file_re: ../../data/v2.0/re.txt
