file_train1: ../../data/cikm_spanish_train_20180516.txt
file_train2: ../../data/cikm_english_train_20180516.txt
file_test: ../../data/cikm_test_a_20180516.txt
file_ft_train: ../../data/v1.0/ft_train.txt
file_ft_train_split: ../../data/v1.0/ft_train_split.txt
file_ft_test: ../../data/v1.0/ft_test.txt
file_ft_val: ../../data/v1.0/ft_val.txt
file_es_vec: ../../data/fast_text_vectors_wiki.es.vec/wiki.es.vec
file_model: ../../data/v1.0/ft_model.bin
file_re: ../../data/v1.0/re.txt
